### ISSUE TITLE
PDF generator for Mozilla Science Study Group Onboarding book

### ISSUE THREAD

**Issue by ceefour** [mozillascience/study-group-onboarding#25]
Some people (like me, or most people in Indonesia where internet connection is limited, or people who prefer paper) need PDF version.

**Comment by zee-moz** [comment]
@ceefour  we've been super busy with Mozfest planning in the last week or so, but I haven't forgotten about this request! @auremoser do you have time to check in next week? @acabunoc do you have any ideas about how we might generate a PDF from GitBook (for the full book, not PDF per page). Thanks-- looking forward to getting this feature up and running soon. 😸

**Comment by RaoOfPhysics** [comment]
@zee-moz: This should do it? https://toolchain.gitbook.com/ebook.html

**Comment by auremoser** [comment]
Yep, right on @RaoOfPhysics ! I think it's also possible to do a batch button via this single page [plugin](https://plugins.gitbook.com/plugin/download-pdf) but I'll def get it done after Mozfest. And @ceefour thank you for offering in the gitter chat, PRs are always welcome :)

**Comment by auremoser** [comment]
@ceefour ! You can find the current generated Gitbook here: https://github.com/mozillascience/study-group-orientation/blob/master/mybook.pdf.

The images are not that great, because the generation tool kind of chops anything embedded or interactive, like the study group map, or the video embeds.

I'll try to generate and update the pdf with each addition to the gitbook, but you can also clone the repo yourself, and do the following (on a mac, other [advice for linux here]()):
- download [Calibre](https://calibre-ebook.com/download) and add it to your applications
- Run this in your terminal : `ln -s /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/local/bin`
- Run `ebook-convert --help` to get instructions
- cd into your `study-group-orientation` clone and run `gitbook pdf ./ ./mybook.pdf`

And voilà, you have your own book! I included the instructions because there were some bugs in the toolchain instructions, this [Stack Overflow post](https://github.com/GitbookIO/gitbook/issues/333) should get you sorted. No need to do it yourself, since I'll maintain the one in our base repo, which you can just download, but I thought you might like to know in case you want to generate your own pdfs. 

Thanks so much for your patience, closing this issue, for now!

**Comment by ceefour** [comment]
Wow cool!

I truly appreciate the time and effort that you have put into this. And the
research you've done to properly workaround the issues.

:)
